In [3]:
#importing the libraries
import pandas as pd
import numpy as np

In [4]:
# load excel 
df=pd.read_excel(r"C:\Users\piyus\Desktop\OTT Dummy Data\OTT Dummy Data\OTT_Unclean_Project.xlsx")

In [5]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20

In [6]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'Title', 'Content_Type', 'Genre',
       'Country', 'Subscription_Plan', 'Device', 'Payment_Method',
       'Account_Status', 'Join_Date', 'Last_Watch_Date', 'Watch_Hours',
       'Monthly_Fee', 'Movies_Watched', 'Episodes_Watched', 'Avg_Rating',
       'Monthly_Sessions', 'Download_Count'],
      dtype='str')

In [7]:
#Initial Exploration

df.shape

(1013, 20)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1013 entries, 0 to 1012
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1013 non-null   str
 1   Customer_Name      1013 non-null   str
 2   Age                1013 non-null   int64
 3   Title              1013 non-null   str
 4   Content_Type       1013 non-null   str
 5   Genre              1010 non-null   str
 6   Country            1013 non-null   str
 7   Subscription_Plan  1013 non-null   str
 8   Device             1009 non-null   str
 9   Payment_Method     1008 non-null   str
 10  Account_Status     1013 non-null   str
 11  Join_Date          1013 non-null   datetime64[us]
 12  Last_Watch_Date    1013 non-null   datetime64[us]
 13  Watch_Hours        1013 non-null   float64
 14  Monthly_Fee        1013 non-null   int64
 15  Movies_Watched     1013 non-null   int64
 16  Episodes_Watched   1013 non-null   int64
 17  Avg_Rating         1013 non-null   float64
 18  Monthly_Sessions   1013 non-null   int64
 19  Download_Count     1013 non-null   int64
dtypes: datetime64[us](2), float64(2), int64(6), str(10)
memory usage: 158.4 KB

In [9]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1013.000000,1013,1013,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000
mean,42.063179,2023-12-16 10:21:12.260612,2024-11-27 19:59:45.784797,42.417473,436.222113,18.187562,59.834156,3.752419,16.686081,12.472853
min,-10.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-08 00:00:00,2023-12-26 00:00:00,25.700000,149.000000,9.000000,31.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-29 00:00:00,2024-12-03 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,53.000000,2024-12-13 00:00:00,2025-11-14 00:00:00,58.100000,649.000000,27.000000,91.000000,4.400000,24.000000,19.000000
max,200.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,15.245811,NaN,NaN,23.988529,214.348252,10.123758,34.895300,0.722812,8.290083,7.577303

In [10]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Age,1013.0,42.063179,-10.0,30.0,43.0,53.0,200.0,15.245811
Join_Date,1013,2023-12-16 10:21:12.260612,2022-01-01 00:00:00,2022-12-08 00:00:00,2023-12-29 00:00:00,2024-12-13 00:00:00,2025-11-01 00:00:00,NaN
Last_Watch_Date,1013,2024-11-27 19:59:45.784797,2022-01-21 00:00:00,2023-12-26 00:00:00,2024-12-03 00:00:00,2025-11-14 00:00:00,2027-08-18 00:00:00,NaN
Watch_Hours,1013.0,42.417473,-20.0,25.7,42.3,58.1,138.3,23.988529
Monthly_Fee,1013.0,436.222113,-649.0,149.0,499.0,649.0,649.0,214.348252
Movies_Watched,1013.0,18.187562,1.0,9.0,18.0,27.0,35.0,10.123758
Episodes_Watched,1013.0,59.834156,0.0,31.0,59.0,91.0,120.0,34.8953
Avg_Rating,1013.0,3.752419,2.5,3.1,3.7,4.4,5.0,0.722812
Monthly_Sessions,1013.0,16.686081,2.0,10.0,17.0,24.0,30.0,8.290083
Download_Count,1013.0,12.472853,0.0,6.0,12.0,19.0,25.0,7.577303

In [11]:
# missing values
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                3
Country              0
Subscription_Plan    0
Device               4
Payment_Method       5
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [12]:
# Duplicate records

df.duplicated().sum()

np.int64(5)

In [13]:
print(df.query("Customer_ID == 'CUST10011'"))

    Customer_ID Customer_Name  Age      Title Content_Type  Genre  \
62    CUST10011   Customer 11   19  Wednesday      TV Show  Crime
134   CUST10011   Customer 11   19  Wednesday      TV Show  Crime

         Country Subscription_Plan  Device Payment_Method Account_Status  \
62   South Korea          Standard  Mobile    Credit Card      Cancelled
134  South Korea          Standard  Mobile    Credit Card      Cancelled

     Join_Date Last_Watch_Date  Watch_Hours  Monthly_Fee  Movies_Watched  \
62  2024-09-27      2024-12-17         30.4          499               6
134 2024-09-27      2024-12-17         30.4          499               6

     Episodes_Watched  Avg_Rating  Monthly_Sessions  Download_Count
62                 93         3.7                 4              24
134                93         3.7                 4              24

In [14]:
print(df[df.duplicated()])

    Customer_ID Customer_Name  Age        Title Content_Type    Genre  \
134   CUST10011   Customer 11   19    Wednesday      TV Show    Crime
495   CUST10101  Customer 101   37        Elite      TV Show    Drama
577   CUST10051   Customer 51   51    Cobra Kai      TV Show   Comedy
703   CUST10151  Customer 151   38    The Crown      TV Show   Comedy
903   CUST10026   Customer 26   31  The Witcher        Movie  Romance

            Country Subscription_Plan    Device Payment_Method Account_Status  \
134     South Korea          Standard    Mobile    Credit Card      Cancelled
495           India           Premium    Laptop     Debit Card         Active
577     South Korea           Premium    Laptop    Credit Card         Active
703  United Kingdom          Standard    Tablet         PayPal         Active
903          Canada             Basic  Smart TV    Net Banking      Cancelled

     Join_Date Last_Watch_Date  Watch_Hours  Monthly_Fee  Movies_Watched  \
134 2024-09-27      2024-12-17         30.4          499               6
495 2022-06-01      2022-09-02          6.6          649              33
577 2025-04-22      2026-02-26         50.1          649               1
703 2024-11-21      2025-08-03         48.3          499               1
903 2024-01-03      2024-09-02         44.8          149              11

     Episodes_Watched  Avg_Rating  Monthly_Sessions  Download_Count
134                93         3.7                 4              24
495                49         3.7                19              25
577                90         3.8                10               1
703                33         3.5                16              24
903               102         4.5                30              13

In [15]:
df.duplicated(subset=["Customer_ID"]).sum()

np.int64(5)

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
# Dirty Values - N/A , NULL, Blank, space

df.replace(
    ['N/A','NULL','',' '],np.nan,inplace=True
)

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,NaN,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart TV,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [19]:
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                4
Country              1
Subscription_Plan    0
Device               4
Payment_Method       7
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [20]:
# Extra Spaces remove
df=df.apply(lambda x: x.str.strip() if x.dtype=="str" else x)

In [21]:
df.info()

<class 'pandas.DataFrame'>
Index: 1008 entries, 0 to 1012
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1008 non-null   str
 1   Customer_Name      1008 non-null   str
 2   Age                1008 non-null   int64
 3   Title              1008 non-null   str
 4   Content_Type       1008 non-null   str
 5   Genre              1004 non-null   str
 6   Country            1007 non-null   str
 7   Subscription_Plan  1008 non-null   str
 8   Device             1004 non-null   str
 9   Payment_Method     1001 non-null   str
 10  Account_Status     1008 non-null   str
 11  Join_Date          1008 non-null   datetime64[us]
 12  Last_Watch_Date    1008 non-null   datetime64[us]
 13  Watch_Hours        1008 non-null   float64
 14  Monthly_Fee        1008 non-null   int64
 15  Movies_Watched     1008 non-null   int64
 16  Episodes_Watched   1008 non-null   int64
 17  Avg_Rating         1008 non-null   float64
 18  Monthly_Sessions   1008 non-null   int64
 19  Download_Count     1008 non-null   int64
dtypes: datetime64[us](2), float64(2), int64(6), str(10)
memory usage: 165.4 KB

In [22]:
df['Country'].value_counts()

Country
Spain             109
United States     107
Germany           104
Canada            103
United Kingdom    101
Japan             100
France             97
India              97
South Korea        95
Australia          91
SOUTH KOREA         1
FRANCE              1
UNITED KINGDOM      1
Name: count, dtype: int64

In [23]:
df['Title'].value_counts()

Title
Dark                    66
Elite                   64
Wednesday               62
Peaky Blinders          55
You                     53
The Umbrella Academy    52
Sex Education           52
Narcos                  50
Ozark                   50
Squid Game              49
Lupin                   49
Cobra Kai               48
The Crown               48
Bridgerton              47
Money Heist             47
Black Mirror            47
The Witcher             46
The Queen's Gambit      46
Lucifer                 42
Stranger Things         35
Name: count, dtype: int64

In [24]:
# Standarize type

df["Content_Type"]=df["Content_Type"].str.title()
df["Customer_ID"]=df["Customer_ID"].str.title()
df["Customer_Name"]=df["Customer_Name"].str.title()
df["Title"]=df["Title"].str.title()
df["Genre"]=df["Genre"].str.title()
df["Country"]=df["Country"].str.title()
df["Subscription_Plan"]=df["Subscription_Plan"].str.title()
df["Device"]=df["Device"].str.title()
df["Payment_Method"]=df["Payment_Method"].str.title()
df["Account_Status"]=df["Account_Status"].str.title()

In [25]:
# Numeric Columns

numeric_cols = ['Age', 'Watch_Hours','Monthly_Fee', 'Movies_Watched','Episodes_Watched', 'Avg_Rating','Monthly_Sessions', 'Download_Count']

In [26]:
for col in numeric_cols:
    df[col]=pd.to_numeric(df[col],errors='coerce')

In [27]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1008.000000,1008,1008,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000
mean,42.097222,2023-12-15 20:42:51.428571,2024-11-28 00:20:00,42.449107,435.960317,18.226190,59.766865,3.751984,16.690476,12.448413
min,-10.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-07 18:00:00,2023-12-25 12:00:00,25.650000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-28 00:00:00,2024-12-03 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,54.000000,2024-12-13 00:00:00,2025-11-14 06:00:00,58.100000,649.000000,27.000000,90.250000,4.400000,24.000000,19.000000
max,200.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,15.258334,NaN,NaN,24.016448,214.461100,10.099231,34.916046,0.724172,8.287380,7.559714

In [28]:
df=df[(df['Age']>=18)& (df['Age']<=100)]

In [29]:
df['Age'].describe()

count    1003.000000
mean       41.973081
std        13.811906
min        18.000000
25%        30.000000
50%        43.000000
75%        53.500000
max        65.000000
Name: Age, dtype: float64

In [30]:
# Negative Values

df=df[df['Watch_Hours']>=0]
df=df[df['Monthly_Fee']>=0]

In [31]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,995.000000,995,995,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000
mean,41.920603,2023-12-16 04:27:44.321608,2024-11-27 13:52:09.648241,42.605126,438.396985,18.217085,59.514573,3.754573,16.701508,12.460302
min,18.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,0.000000,149.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-09 00:00:00,2023-12-26 00:00:00,25.700000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-28 00:00:00,2024-12-02 00:00:00,42.300000,499.000000,18.000000,58.000000,3.700000,17.000000,12.000000
75%,53.000000,2024-12-10 00:00:00,2025-11-12 00:00:00,58.100000,649.000000,27.000000,90.000000,4.400000,24.000000,19.000000
max,65.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,13.797644,NaN,NaN,23.784772,209.136478,10.085605,34.855299,0.723983,8.280686,7.564557

In [32]:
df.shape

(995, 20)

In [33]:
# Date Cleaning

df['Join_Date']=pd.to_datetime(df['Join_Date'],errors='coerce')

df['Last_Watch_Date']=pd.to_datetime(df['Last_Watch_Date'],errors='coerce')

In [34]:
df.info()

<class 'pandas.DataFrame'>
Index: 995 entries, 0 to 1012
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        995 non-null    str
 1   Customer_Name      995 non-null    str
 2   Age                995 non-null    int64
 3   Title              995 non-null    str
 4   Content_Type       995 non-null    str
 5   Genre              991 non-null    str
 6   Country            994 non-null    str
 7   Subscription_Plan  995 non-null    str
 8   Device             991 non-null    str
 9   Payment_Method     988 non-null    str
 10  Account_Status     995 non-null    str
 11  Join_Date          995 non-null    datetime64[us]
 12  Last_Watch_Date    995 non-null    datetime64[us]
 13  Watch_Hours        995 non-null    float64
 14  Monthly_Fee        995 non-null    int64
 15  Movies_Watched     995 non-null    int64
 16  Episodes_Watched   995 non-null    int64
 17  Avg_Rating         995 non-null    float64
 18  Monthly_Sessions   995 non-null    int64
 19  Download_Count     995 non-null    int64
dtypes: datetime64[us](2), float64(2), int64(6), str(10)
memory usage: 163.2 KB

In [35]:
df[["Join_Date","Last_Watch_Date"]].isnull().sum()

Join_Date          0
Last_Watch_Date    0
dtype: int64

In [36]:
# Missing Values

df['Age']=df['Age'].fillna(df["Age"].mean(), inplace=True)
df['Watch_Hours']=df['Watch_Hours'].fillna(df['Watch_Hours'].mean(), inplace=True)
df['Monthly_Fee']=df['Monthly_Fee'].fillna(df['Monthly_Fee'].mean(),inplace=True)

C:\Users\piyus\AppData\Local\Temp\ipykernel_17512\1799458801.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age']=df['Age'].fillna(df["Age"].mean(), inplace=True)
C:\Users\piyus\AppData\Local\Temp\ipykernel_17512\1799458801.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Watch_Hours']=df['Watch_Hours'].fillna(df['Watch_Hours'].mean(), inplace=True)
C:\Users\piyus\AppData\Local\Temp\ipykernel_17512\1799458801.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Monthly_Fee']=df['Monthly_Fee'].fillna(df['Monthly_Fee'].mean(),inplace=True)

In [37]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,995.000000,995,995,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000
mean,41.920603,2023-12-16 04:27:44.321608,2024-11-27 13:52:09.648241,42.605126,438.396985,18.217085,59.514573,3.754573,16.701508,12.460302
min,18.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,0.000000,149.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-09 00:00:00,2023-12-26 00:00:00,25.700000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-28 00:00:00,2024-12-02 00:00:00,42.300000,499.000000,18.000000,58.000000,3.700000,17.000000,12.000000
75%,53.000000,2024-12-10 00:00:00,2025-11-12 00:00:00,58.100000,649.000000,27.000000,90.000000,4.400000,24.000000,19.000000
max,65.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,13.797644,NaN,NaN,23.784772,209.136478,10.085605,34.855299,0.723983,8.280686,7.564557

In [38]:
df['Payment_Method']=df['Payment_Method'].fillna("Unknown",inplace=True)
df['Device']=df['Device'].fillna("Unknown",inplace=True)
df['Genre']=df['Genre'].fillna("Unknown",inplace=True)

C:\Users\piyus\AppData\Local\Temp\ipykernel_17512\415030976.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Payment_Method']=df['Payment_Method'].fillna("Unknown",inplace=True)
C:\Users\piyus\AppData\Local\Temp\ipykernel_17512\415030976.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Device']=df['Device'].fillna("Unknown",inplace=True)
C:\Users\piyus\AppData\Local\Temp\ipykernel_17512\415030976.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Genre']=df['Genre'].fillna("Unknown",inplace=True)

In [39]:
# Feature Engineering

# Customer Revenue
df['Customer_Revenue']=df['Monthly_Fee'] * df['Monthly_Sessions']

In [40]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue
0,Cust10927,Customer 927,25,Bridgerton,Tv Show,Drama,Japan,Premium,Gaming Console,Paypal,...,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3,7139
1,Cust10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,...,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19,3278
2,Cust10683,Customer 683,40,Money Heist,Tv Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3,3874
3,Cust10515,Customer 515,44,You,Tv Show,Action,Spain,Premium,Gaming Console,Credit Card,...,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9,17523
4,Cust10366,Customer 366,57,The Witcher,Tv Show,Comedy,Canada,Premium,Smart Tv,Credit Card,...,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20,9735

In [41]:
# Engagement Score

df['Engagement_Score']=(df['Watch_Hours']+df['Monthly_Sessions']+df['Download_Count'])

In [42]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score
0,Cust10927,Customer 927,25,Bridgerton,Tv Show,Drama,Japan,Premium,Gaming Console,Paypal,...,2024-12-21,28.0,649,5,97,3.6,11,3,7139,42.0
1,Cust10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,...,2024-08-14,0.0,149,5,84,4.5,22,19,3278,41.0
2,Cust10683,Customer 683,40,Money Heist,Tv Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,2025-10-31,28.9,149,16,106,3.8,26,3,3874,57.9
3,Cust10515,Customer 515,44,You,Tv Show,Action,Spain,Premium,Gaming Console,Credit Card,...,2023-06-18,27.6,649,10,24,2.6,27,9,17523,63.6
4,Cust10366,Customer 366,57,The Witcher,Tv Show,Comedy,Canada,Premium,Smart Tv,Credit Card,...,2025-06-09,32.0,649,10,78,3.2,15,20,9735,67.0

In [43]:
# Watch Category 

bins=[0,20,50,100,np.inf]
label=['Low','Medium','High','Very High']

df['Watch_Category']=pd.cut(df['Watch_Hours'],bins=bins,labels=label)

In [44]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category
0,Cust10927,Customer 927,25,Bridgerton,Tv Show,Drama,Japan,Premium,Gaming Console,Paypal,...,28.0,649,5,97,3.6,11,3,7139,42.0,Medium
1,Cust10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,...,0.0,149,5,84,4.5,22,19,3278,41.0,NaN
2,Cust10683,Customer 683,40,Money Heist,Tv Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,28.9,149,16,106,3.8,26,3,3874,57.9,Medium
3,Cust10515,Customer 515,44,You,Tv Show,Action,Spain,Premium,Gaming Console,Credit Card,...,27.6,649,10,24,2.6,27,9,17523,63.6,Medium
4,Cust10366,Customer 366,57,The Witcher,Tv Show,Comedy,Canada,Premium,Smart Tv,Credit Card,...,32.0,649,10,78,3.2,15,20,9735,67.0,Medium

In [45]:
df['Watch_Category'].value_counts()

Watch_Category
Medium       449
High         357
Low          142
Very High     10
Name: count, dtype: int64

In [46]:
# Customer Age Group

bins=[17,25,35,50,100]
label=['18-25','26-35','36-50','51+']

df["Age_Group"]=pd.cut(df['Age'],bins=bins,labels=label)

In [47]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category,Age_Group
0,Cust10927,Customer 927,25,Bridgerton,Tv Show,Drama,Japan,Premium,Gaming Console,Paypal,...,649,5,97,3.6,11,3,7139,42.0,Medium,18-25
1,Cust10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,...,149,5,84,4.5,22,19,3278,41.0,NaN,36-50
2,Cust10683,Customer 683,40,Money Heist,Tv Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,149,16,106,3.8,26,3,3874,57.9,Medium,36-50
3,Cust10515,Customer 515,44,You,Tv Show,Action,Spain,Premium,Gaming Console,Credit Card,...,649,10,24,2.6,27,9,17523,63.6,Medium,36-50
4,Cust10366,Customer 366,57,The Witcher,Tv Show,Comedy,Canada,Premium,Smart Tv,Credit Card,...,649,10,78,3.2,15,20,9735,67.0,Medium,51+

In [48]:
df['Age_Group'].value_counts()

Age_Group
51+      325
36-50    308
26-35    215
18-25    147
Name: count, dtype: int64

In [49]:
# Account Activ Flag

df['Active_Flag']=np.where(df['Account_Status']=='Active',1,0)

In [50]:
# Final Data Quality Check

df.info()

<class 'pandas.DataFrame'>
Index: 995 entries, 0 to 1012
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        995 non-null    str
 1   Customer_Name      995 non-null    str
 2   Age                995 non-null    int64
 3   Title              995 non-null    str
 4   Content_Type       995 non-null    str
 5   Genre              995 non-null    str
 6   Country            994 non-null    str
 7   Subscription_Plan  995 non-null    str
 8   Device             995 non-null    str
 9   Payment_Method     995 non-null    str
 10  Account_Status     995 non-null    str
 11  Join_Date          995 non-null    datetime64[us]
 12  Last_Watch_Date    995 non-null    datetime64[us]
 13  Watch_Hours        995 non-null    float64
 14  Monthly_Fee        995 non-null    int64
 15  Movies_Watched     995 non-null    int64
 16  Episodes_Watched   995 non-null    int64
 17  Avg_Rating         995 non-null    float64
 18  Monthly_Sessions   995 non-null    int64
 19  Download_Count     995 non-null    int64
 20  Customer_Revenue   995 non-null    int64
 21  Engagement_Score   995 non-null    float64
 22  Watch_Category     958 non-null    category
 23  Age_Group          995 non-null    category
 24  Active_Flag        995 non-null    int64
dtypes: category(2), datetime64[us](2), float64(3), int64(8), str(10)
memory usage: 188.9 KB

In [51]:
df.isnull().sum()

Customer_ID           0
Customer_Name         0
Age                   0
Title                 0
Content_Type          0
Genre                 0
Country               1
Subscription_Plan     0
Device                0
Payment_Method        0
Account_Status        0
Join_Date             0
Last_Watch_Date       0
Watch_Hours           0
Monthly_Fee           0
Movies_Watched        0
Episodes_Watched      0
Avg_Rating            0
Monthly_Sessions      0
Download_Count        0
Customer_Revenue      0
Engagement_Score      0
Watch_Category       37
Age_Group             0
Active_Flag           0
dtype: int64

In [52]:
df[df['Country'].isna()]

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category,Age_Group,Active_Flag
155,Cust10946,Customer 946,48,You,Movie,Sci-Fi,NaN,Premium,Mobile,Paypal,...,7,45,3.4,11,2,7139,28.2,Low,36-50,0

In [53]:
pd.set_option('display.max_columns', None)

In [54]:
df[df['Watch_Category'].isna()]

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category,Age_Group,Active_Flag
1,Cust10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19,3278,41.0,NaN,36-50,1
36,Cust10934,Customer 934,56,Lupin,Tv Show,Drama,United States,Basic,Mobile,Debit Card,Active,2023-07-28,2024-08-10,0.0,149,29,118,3.2,17,4,2533,21.0,NaN,51+,1
61,Cust10430,Customer 430,49,The Witcher,Tv Show,Documentary,Canada,Basic,Gaming Console,Debit Card,Active,2025-03-29,2025-05-07,0.0,149,31,90,3.4,20,15,2980,35.0,NaN,36-50,1
174,Cust10111,Customer 111,46,Black Mirror,Movie,Documentary,India,Basic,Smart Tv,Net Banking,Active,2023-03-31,2024-04-30,0.0,149,6,47,3.1,12,3,1788,15.0,NaN,36-50,1
177,Cust10526,Customer 526,38,Lucifer,Movie,Comedy,France,Basic,Laptop,Credit Card,Active,2025-04-29,2026-05-21,0.0,149,15,2,4.9,19,20,2831,39.0,NaN,36-50,1
180,Cust10545,Customer 545,24,Elite,Tv Show,Romance,Spain,Standard,Gaming Console,Upi,Cancelled,2024-04-25,2024-05-12,0.0,499,8,94,4.2,7,25,3493,32.0,NaN,18-25,0
190,Cust10222,Customer 222,53,Elite,Movie,Romance,South Korea,Standard,Laptop,Net Banking,Cancelled,2022-06-26,2024-03-25,0.0,499,16,59,3.4,17,24,8483,41.0,NaN,51+,0
218,Cust10669,Customer 669,25,Bridgerton,Movie,Drama,Canada,Basic,Smart Tv,Debit Card,Active,2025-09-10,2026-01-20,0.0,149,14,83,2.9,19,8,2831,27.0,NaN,18-25,1
225,Cust10050,Customer 50,35,Lucifer,Tv Show,Thriller,United States,Standard,Tablet,Debit Card,Active,2024-07-18,2026-01-18,0.0,499,12,24,3.0,17,8,8483,25.0,NaN,26-35,1
269,Cust10383,Customer 383,57,Dark,Movie,Documentary,Australia,Premium,Gaming Console,Upi,Active,2024-09-16,2024-11-17,0.0,649,19,25,4.5,21,8,13629,29.0,NaN,51+,1
287,Cust10722,Customer 722,43,Ozark,Movie,Drama,Japan,Premium,Smart Tv,Credit Card,Active,2025-08-07,2025-11-22,0.0,649,5,46,4.0,29,10,18821,39.0,NaN,36-50,1
303,Cust10443,Customer 443,38,You,Movie,Comedy,Spain,Premium,Mobile,Paypal,Active,2025-09-29,2025-11-30,0.0,649,17,104,3.2,16,2,10384,18.0,NaN,36-50,1
307,Cust10569,Customer 569,43,Lupin,Tv Show,Crime,Australia,Premium,Smart Tv,Unknown,Paused,2024-12-13,2026-04-29,0.0,649,27,105,2.9,18,4,11682,22.0,NaN,36-50,0
322,Cust10080,Customer 80,46,Elite,Movie,Romance,United States,Standard,Laptop,Net Banking,Paused,2023-03-21,2025-01-10,0.0,499,23,7,3.5,8,3,3992,11.0,NaN,36-50,0
432,Cust10286,Customer 286,56,The Queen'S Gambit,Tv Show,Sci-Fi,United States,Premium,Mobile,Credit Card,Active,2025-06-23,2026-06-22,0.0,649,19,70,3.8,24,3,15576,27.0,NaN,51+,1
435,Cust10992,Customer 992,59,Narcos,Tv Show,Romance,United Kingdom,Standard,Smart Tv,Credit Card,Active,2025-01-23,2026-10-27,0.0,499,28,51,3.6,4,15,1996,19.0,NaN,51+,1
443,Cust10576,Customer 576,52,Bridgerton,Movie,Crime,South Korea,Basic,Tablet,Net Banking,Active,2025-09-10,2027-03-11,0.0,149,21,51,4.0,17,0,2533,17.0,NaN,51+,1
462,Cust10075,Customer 75,26,Peaky Blinders,Tv Show,Horror,Canada,Basic,Laptop,Credit Card,Active,2023-02-16,2024-06-24,0.0,149,19,95,4.7,27,3,4023,30.0,NaN,26-35,1
485,Cust10397,Customer 397,43,The Umbrella Academy,Tv Show,Sci-Fi,India,Premium,Tablet,Paypal,Active,2022-10-05,2023-04-30,0.0,649,30,11,3.1,24,20,15576,44.0,NaN,36-50,1
526,Cust10432,Customer 432,58,Peaky Blinders,Tv Show,Animation,India,Basic,Laptop,Net Banking,Cancelled,2025-11-01,2027-02-25,0.0,149,30,65,4.8,20,23,2980,43.0,NaN,51+,0
544,Cust10237,Customer 237,26,Squid Game,Movie,Romance,India,Premium,Mobile,Credit Card,Active,2023-02-17,2023-07-13,0.0,649,8,108,3.8,13,2,8437,15.0,NaN,26-35,1
565,Cust10741,Customer 741,25,The Queen'S Gambit,Tv Show,Documentary,France,Standard,Laptop,Debit Card,Cancelled,2024-10-25,2026-01-05,0.0,499,34,97,3.3,7,14,3493,21.0,NaN,18-25,0
643,Cust10976,Customer 976,57,Lupin,Movie,Romance,South Korea,Premium,Smart Tv,Upi,Active,2023-08-25,2024-01-31,0.0,649,18,3,3.7,28,22,18172,50.0,NaN,51+,1
646,Cust10038,Customer 38,22,The Umbrella Academy,Tv Show,Romance,Canada,Premium,Smart Tv,Paypal,Active,2023-03-15,2024-05-19,0.0,649,25,115,4.4,24,0,15576,24.0,NaN,18-25,1
652,Cust10709,Customer 709,39,The Queen'S Gambit,Movie,Thriller,India,Basic,Gaming Console,Debit Card,Active,2023-09-22,2024-01-27,0.0,149,2,105,2.6,19,9,2831,28.0,NaN,36-50,1
699,Cust10263,Customer 263,30,Dark,Movie,Drama,Australia,Premium,Smart Tv,Debit Card,Active,2023-09-04,2023-10-01,0.0,649,32,37,3.1,15,12,9735,27.0,NaN,26-35,1
722,Cust10609,Customer 609,43,Lupin,Movie,Thriller,South Korea,Standard,Tablet,Paypal,Cancelled,2025-04-05,2026-05-16,0.0,499,14,39,3.6,14,18,6986,32.0,NaN,36-50,0
733,Cust10439,Customer 439,59,You,Tv Show,Crime,Spain,Standard,Mobile,Debit Card,Active,2025-06-04,2026-07-10,0.0,499,30,98,4.2,9,23,4491,32.0,NaN,51+,1
758,Cust10978,Customer 978,44,Bridgerton,Tv Show,Animation,France,Premium,Laptop,Debit Card,Cancelled,2023-01-29,2023-10-26,0.0,649,28,47,3.4,9,10,5841,19.0,NaN,36-50,0
769,Cust10672,Customer 672,20,Narcos,Movie,Crime,South Korea,Basic,Tablet,Net Banking,Active,2023-05-01,2024-12-27,0.0,149,23,35,2.8,21,13,3129,34.0,NaN,18-25,1
821,Cust10734,Customer 734,49,Narcos,Tv Show,Comedy,Spain,Standard,Smart Tv,Upi,Active,2025-05-22,2026-09-16,0.0,499,10,81,3.0,20,1,9980,21.0,NaN,36-50,1
873,Cust10472,Customer 472,28,You,Movie,Action,Germany,Basic,Tablet,Unknown,Active,2022-08-12,2024-05-16,0.0,149,2,37,3.5,23,17,3427,40.0,NaN,26-35,1
882,Cust10015,Customer 15,33,The Queen'S Gambit,Tv Show,Thriller,United States,Premium,Mobile,Paypal,Active,2024-08-26,2025-10-21,0.0,649,30,110,4.3,23,20,14927,43.0,NaN,26-35,1
938,Cust10014,Customer 14,32,The Crown,Movie,Romance,United States,Premium,Gaming Console,Credit Card,Active,2022-05-01,2023-09-11,0.0,649,14,69,2.8,30,18,19470,48.0,NaN,26-35,1
946,Cust10647,Customer 647,22,The Umbrella Academy,Tv Show,Crime,France,Basic,Tablet,Credit Card,Active,2022-07-18,2022-12-03,0.0,149,13,62,3.0,5,14,745,19.0,NaN,18-25,1
953,Cust10567,Customer 567,63,Peaky Blinders,Movie,Romance,Spain,Premium,Laptop,Net Banking,Active,2025-03-04,2026-03-26,0.0,649,34,94,3.1,12,16,7788,28.0,NaN,51+,1
1006,Cust55543,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19,3278,41.0,NaN,36-50,1

In [55]:
print(df['Watch_Hours'].head())

0    28.0
1     0.0
2    28.9
3    27.6
4    32.0
Name: Watch_Hours, dtype: float64

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Age,995.0,41.920603,18.0,30.0,43.0,53.0,65.0,13.797644
Join_Date,995,2023-12-16 04:27:44.321608,2022-01-01 00:00:00,2022-12-09 00:00:00,2023-12-28 00:00:00,2024-12-10 00:00:00,2025-11-01 00:00:00,NaN
Last_Watch_Date,995,2024-11-27 13:52:09.648241,2022-01-21 00:00:00,2023-12-26 00:00:00,2024-12-02 00:00:00,2025-11-12 00:00:00,2027-08-18 00:00:00,NaN
Watch_Hours,995.0,42.605126,0.0,25.7,42.3,58.1,138.3,23.784772
Monthly_Fee,995.0,438.396985,149.0,149.0,499.0,649.0,649.0,209.136478
Movies_Watched,995.0,18.217085,1.0,9.0,18.0,27.0,35.0,10.085605
Episodes_Watched,995.0,59.514573,0.0,30.0,58.0,90.0,120.0,34.855299
Avg_Rating,995.0,3.754573,2.5,3.1,3.7,4.4,5.0,0.723983
Monthly_Sessions,995.0,16.701508,2.0,10.0,17.0,24.0,30.0,8.280686
Download_Count,995.0,12.460302,0.0,6.0,12.0,19.0,25.0,7.564557
Customer_Revenue,995.0,7339.680402,298.0,2682.0,5841.0,11477.0,19470.0,5344.095657
Engagement_Score,995.0,71.766935,11.0,51.2,71.7,90.05,167.3,26.20257
Active_Flag,995.0,0.708543,0.0,0.0,1.0,1.0,1.0,0.454662

In [58]:
# Clean CSV Export

df.to_csv('Netflix_Clean_Data.csv',index=False)

In [61]:
from sqlalchemy import create_engine

engine=create_engine('mysql+pymysql://root:Qwerty%23%40123@localhost/netflix_db')

In [62]:
df.to_sql(
    'netflix_customers',
    con=engine,
    if_exists='replace',
    index=False
)

995

In [ ]:
# https://github.com/piyush8769/OTT-Platform-Subscription-Customer-Engagement-Analytics.git